#!/bin/bash

set -xeuo pipefail

cp -avf "/ctx/system_files"/. /

##########################################
# Step 1 - Package Installs and Removals #
##########################################

#nuke kde, sddm, and xwaylandvideobridge
systemctl disable sddm.service

dnf5 remove -y sddm
dnf5 remove -y plasma-* kde-*
dnf5 remove -y xwaylandvideobridge

#install niri
dnf5 -y copr enable yalter/niri
dnf5 -y copr disable yalter/niri
echo "priority=1" | tee -a /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:yalter:niri.repo
dnf5 -y --enablerepo copr:copr.fedorainfracloud.org:yalter:niri install niri

#install quickshell
dnf5 -y copr enable errornointernet/quickshell
dnf5 -y copr disable errornointernet/quickshell
dnf5 -y --enablerepo copr:copr.fedorainfracloud.org:errornointernet:quickshell install quickshell

#install dank linux toolkit
dnf5 -y copr enable avengemedia/danklinux
dnf5 -y copr disable avengemedia/danklinux
dnf5 -y --enablerepo copr:copr.fedorainfracloud.org:avengemedia:danklinux install \
    breakpad \
    cliphist \
    danksearch \
    dgop \
    dms-greeter \
    hyprpicker \
    material-symbols-fonts \
    matugen

#install dms
dnf5 -y copr enable avengemedia/dms
dnf5 -y copr disable avengemedia/dms
dnf5 -y --enablerepo copr:copr.fedorainfracloud.org:avengemedia:dms install \
    dms \
    dms-cli \
    dms-greeter

#install greetd
dnf5 -y install --skip-unavailable\
    greetd \
    tuigreet \
    greetd-selinux \

#install basic utils
dnf5 -y install --skip-unavailable\
    polkit-kde \
    brightnessctl \
    cava \
    wl-clipboard \
    gammastep \
    sassc \
    libappstream-glib \
    gnome-keyring \
    xwayland-satellite

#install theming stuff
dnf5 -y install --skip-unavailable\
    adw-gtk3-theme \
    nwg-look \
    qt6-qtmultimedia \
    qt6ct \
    qt5ct

#portals, more xdgs, and dolphin
dnf5 -y install --skip-unavailable \
    xdg-desktop-portal-gnome \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-kde \
    xdg-user-dirs \
    dolphin

#########################
# Step 2 - Configure DM #
#########################

#use gnome keyring for greetd
sed -i '/gnome_keyring.so/ s/-auth/auth/ ; /gnome_keyring.so/ s/-session/session/' /etc/pam.d/greetd
cat /etc/pam.d/greetd

#enable greetd systemd stuff
systemctl enable greetd
systemctl enable dms-greeter-folder-create.service

#########################
# Step 3 - Configure TM #
#########################

#configure polkit agent
sed -i "s/After=.*/After=graphical-session.target/" /usr/lib/systemd/user/plasma-polkit-agent.service

####################################
# Step 4 - Configure SystemD Stuff #
####################################

#configure niri service
add_wants_niri() {
    sed -i "s/\[Unit\]/\[Unit\]\nWants=$1/" "/usr/lib/systemd/user/niri.service"
}
add_wants_niri cliphist.service
add_wants_niri plasma-polkit-agent.service
add_wants_niri xwayland-satellite.service
cat /usr/lib/systemd/user/niri.service

#enable systemd services
systemctl enable --global dms.service
systemctl enable --global cliphist.service
systemctl enable --global gnome-keyring-daemon.socket
systemctl enable --global gnome-keyring-daemon.service
systemctl enable --global plasma-polkit-agent.service
systemctl enable --global xwayland-satellite.service
